### ISSUE TITLE
Create rebar3 dragon plugin

### ISSUE THREAD

**Issue by oubiwann** [lfex/dragon#7]
This should go in the `lfex` Github org as the `rebar3-dragon` project. It should define the following commands initially:
- [ ] - `rebar3 dragon new <project-name>` - Create a new Dragon web app skeleton (see issue https://github.com/lfex/rebar3-dragon/issues/1)
- [ ] - `rebar3 dragon run` - Run a dev server in a Dragon project directory using the configured (or default) web server (see issue https://github.com/lfex/rebar3-dragon/issues/2)
- [ ] - `rebar3 dragon docker` - Build and run a Docker image of a Dragon project  (see issue https://github.com/lfex/rebar3-dragon/issues/3)

**Comment by yurrriq** [comment]
:clap: This project as well as the rebar3 plugin look very promising! I'd be happy to work on the plugin and/or other stuff. Do you have a repo set up yet for the plugin, @oubiwann?

**Comment by oubiwann** [comment]
So glad you think so! Have you seen the placeholder site at http://dragon.lfe.io/?

Let's see, for your other comments, there are several things that need to be done:
- [x] Create lfex Dragon Team
- [x] Add lfex/dragon to Dragon Team
- [x] Create lfex/rebar3-dragon repo
- [x] Create tickets for each of the three tasks listed in the description of this ticket
- [x] Add lfex/rebar3-dragon rpeo to Dragon Team
- [x] Add @yurrriq to Dragon Team :-)

At that point, the rebar3-dragon repo will be empty -- feel free to populate it using one of the lfe-rebar3 plugins from that Github org.

**Comment by oubiwann** [comment]
You're all set, man!

**Comment by yurrriq** [comment]
:tada: Cheers! Yeah, the placeholder site looks great!

**Comment by yurrriq** [comment]
I'm at Erlang Factory this week and going to a show tonight, so I likely won't get to hack on this until tomorrow night, but I'm excited. Are you here or coming Thursday btw?

**Comment by oubiwann** [comment]
Nah, I won't be at Erlang Factory this year. Have fun!
